<?php

namespace AppBundle\Repository;

/**
 * hohoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hohoRepository extends \Doctrine\ORM\EntityRepository
{
  public function getNb() {

        return $this->createQueryBuilder('l')

                        ->select('COUNT(l)')

                        ->getQuery()

                        ->getSingleScalarResult();

    }

}
