# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
parameters:
    upload: '%kernel.project_dir%\upload'
security:
      # ...


    providers:
        our_db_provider:
            entity:
              class: AppBundle:Usr
              property: username

    encoders:

        AppBundle\Entity\Usr:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:

            anonymous: ~
            http_basic: ~

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            form_login:

                login_path: /login
                check_path: /login
                always_use_default_target_path: false
                default_target_path: /

                target_path_parameter: go_to

                username_parameter: _username
                password_parameter: _password

            logout:
                  path: /logout
                  target: /login




    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
      #  - { path: ^/user, roles: ROLE_ADMIN }
      #  - { path: ^/param, roles: ROLE_ADMIN }
      #  - { path: ^/act, roles: ROLE_ADMIN }
      #  - { path: ^/word, roles: ROLE_ADMIN }
      #  - { path: ^/grammer, roles: ROLE_ADMIN }
      #  - { path: ^/files, roles: ROLE_ADMIN }
      #  - { path: ^/res, roles: ROLE_USER }
      #  - { path: ^/profil_user, roles: ROLE_USER }
